# Generated by Django 6.0.2 on 2026-02-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
