# Generated by Django 6.0.2 on 2026-02-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Concert', 'Concert'), ('Conference', 'Conference'), ('Workshop', 'Workshop')], default='Tech', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
