# Generated by Django 6.0.1 on 2026-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_booking_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
